### ISSUE TITLE
Clicking view "search" when already on the view gives error

### ISSUE THREAD

**Issue by fyllekanin** [fyllekanin/io.wowcollector#21]
1. Create a new mount view
2. Go to the mount page and enter the ID
3. Then click the "search" button again, now you instead get that the view doesnt exist

This is wrong because obviously it exists, I searched it a second ago sucessfully

**Comment by rutbergphilip** [comment]
[c689df6](https://github.com/fyllekanin/wowcollector.io/pull/26/commits/c689df6e7dbc488396feb1a6a2f6ceeb5f88b0f1)
