### ISSUE TITLE
Pet and toy view not working

### ISSUE THREAD

**Issue by fyllekanin** [fyllekanin/io.wowcollector#22]
1. Search for example thedrunken-kazzak
2. Go  to pet view
3. You can see in the network log that the response is available
4. Only the category name is rendered, the pets themself are not

**Comment by rutbergphilip** [comment]
[417106d](https://github.com/fyllekanin/wowcollector.io/pull/26/commits/417106d430aabf34a1fb00eee3613f832d224f05)
