### ISSUE TITLE
Release page improvements

### ISSUE THREAD

**Issue by fyllekanin** [fyllekanin/io.wowcollector#23]
Each issue has a tag what it was made for (bug, improvement, feature etc)

This is not visualized on the releases page, right now we have to rely on the description that was given.

Potential ideas:
- Group them, have a header (bug fixes) then list all the bugs under that one (color for the * maybe)
- Update so each release mentions amount of each type that was in the release, then make it clickable and open a more detailed dialog of the release
-- 0.3.0
--- 5 bug fixes, 3 improvements, 2 features

**Comment by rutbergphilip** [comment]
[415dc63](https://github.com/fyllekanin/wowcollector.io/pull/26/commits/415dc63ec22d099ed63eb41c8bde2bda2b03b08d)
